/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofase3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author fping
 */
public class fmrMenuPrincipal extends javax.swing.JFrame {
    private int userId;
    private String nombreUsuario;
    private UsuarioDAO usuarioDAO2;
    /**
     * Creates new form fmrMenuPrincipal
     */
    public fmrMenuPrincipal(int userId) {
        this.userId = userId;
        
        initComponents();
        
        
        
        try {
            Connection conexion = obtenerConexion();  // Método que obtiene la conexión a la base de datos
            usuarioDAO2 = new UsuarioDAO(conexion);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            // Puedes manejar el error de conexión de la manera que prefieras
        }
        
        this.nombreUsuario = obtenerNombreUsuarioDesdeBD(this.userId);
        
        // Actualizar el texto del JLabel con el nombre de usuario
        lblBienvenida.setText("¡Bienvenido, " + nombreUsuario + "!");
    }
    
    // Método para obtener el nombre de usuario desde la base de datos
    private String obtenerNombreUsuarioDesdeBD(int userId) {
        // Llamar al método que obtiene el nombre de usuario por ID
        return usuarioDAO2.obtenerNombreUsuarioPorId(userId);
    }

    private Connection obtenerConexion() throws SQLException {
        // URL de conexión a la base de datos
        String url = "jdbc:sqlserver://DESKTOP-OKOLF5L\\BDD1;databaseName=proyectoisfase2";
        String usuario = "proyectoFase2";
        String contrasena = "proyectoFase2.";

        // Establecer la conexión
        return DriverManager.getConnection(url, usuario, contrasena);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        bCategorias = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú Principal");
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);

        lblBienvenida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBienvenida.setText("jLabel1");

        bCategorias.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bCategorias.setText("Categorias");
        bCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCategoriasActionPerformed(evt);
            }
        });

        bProductos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bProductos.setText("Productos");
        bProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(bCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductosActionPerformed
        // TODO add your handling code here:
        abrirFormularioProductos();
    }//GEN-LAST:event_bProductosActionPerformed

    private void bCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCategoriasActionPerformed
        // TODO add your handling code here:
        abrirFormularioCategorias();
    }//GEN-LAST:event_bCategoriasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void abrirFormularioProductos() {
        // Crea y muestra la pantalla frmProductos
        frmProductos formularioProductos = new frmProductos();
        formularioProductos.setVisible(true);
        formularioProductos.setLocationRelativeTo(null);
    }
    
     private void abrirFormularioCategorias() {
        // Crea y muestra la pantalla frmProductos
        frmCategorias formularioCategorias = new frmCategorias();
        formularioCategorias.setVisible(true);
        formularioCategorias.setLocationRelativeTo(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //fmrMenuPrincipal MenuPrincipal = new fmrMenuPrincipal(0);
                //MenuPrincipal.setVisible(true);
                //MenuPrincipal.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCategorias;
    private javax.swing.JButton bProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
