/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofase3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author fping
 */
public class frmCategorias extends javax.swing.JFrame {

    private CategoriaTableModel modeloTablaCategorias;
    private CategoriaDAO categoriaDAO;
    /**
     * Creates new form frmCategorias
     */
    public frmCategorias() {
        initComponents();
        try {
            Connection conexion = obtenerConexion();
            categoriaDAO = new CategoriaDAO(conexion);
        } catch (SQLException ex) {
            Logger.getLogger(frmCategorias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Crear el modelo de tabla de categorías
        modeloTablaCategorias = new CategoriaTableModel();
        // Llenar la tabla al abrir el frame
        modeloTablaCategorias.clear();
        cargarDatosCategorias();
        
        tablaCategorias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                // Obtén la fila seleccionada
                int filaSeleccionada = tablaCategorias.getSelectedRow();

                if (filaSeleccionada > -1) {
                    // Actualizar el JTextField con los datos de la categoría seleccionada
                    actualizarCampoCategoriaDesdeTabla(filaSeleccionada);
                }
            }
        }
    });
       
    }
    
    private void actualizarCampoCategoriaDesdeTabla(int filaSeleccionada) {
        // Obtén el nombre de la categoría desde la fila seleccionada y la columna deseada (puedes ajustar el índice de columna según tu estructura de datos)
        String nombreCategoria = (String) tablaCategorias.getValueAt(filaSeleccionada, 1);

        // Verifica si el nombre de la categoría no es nulo
        if (nombreCategoria != null) {
            // Actualiza el JTextField con el nombre de la categoría
            tfDescripcion.setText(nombreCategoria); 
        } else {
            // Si el nombre de la categoría es nulo, limpia los campos o realiza alguna otra acción
            tfDescripcion.setText(""); 
        }
    }
    
    private Connection obtenerConexion() throws SQLException {
        // URL de conexión a la base de datos
        String url = "jdbc:sqlserver://DESKTOP-OKOLF5L\\BDD1;databaseName=proyectoisfase2";
        String usuario = "proyectoFase2";
        String contrasena = "proyectoFase2.";

        // Establecer la conexión
        return DriverManager.getConnection(url, usuario, contrasena);
    }

     private void cargarDatosCategorias() {
        List<Categoria> categorias = categoriaDAO.obtenerCategoriasDesdeBaseDeDatos();
        modeloTablaCategorias = new CategoriaTableModel();
        modeloTablaCategorias.clear();
        // Agregar las filas al modelo de categorías
        for (Categoria categoria : categorias) {
            modeloTablaCategorias.agregarFila(
                categoria.getIdCategoria(),
                categoria.getNombreCategoria() 
            );
        }

        // Establecer el modelo en la tabla de categorías
        tablaCategorias.setModel(modeloTablaCategorias);
    }

    private List<Categoria> obtenerCategoriasDesdeBaseDeDatos() {
        // Lógica para obtener las categorías desde la base de datos
        // Puedes usar tu método existente o adaptarlo según tu implementación
        return categoriaDAO.obtenerCategoriasDesdeBaseDeDatos();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAgregar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias");
        setBackground(new java.awt.Color(204, 255, 255));

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        lblDescripcion.setText("Descripción");

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDescripcion))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addGap(16, 16, 16)
                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        agregarCategoria();
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        editarCategoria();
    }//GEN-LAST:event_bEditarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        buscarCategoria();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        borrarCategoria();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void agregarCategoria() {
        // Obtén los valores de los campos
        String nombreCategoria = tfDescripcion.getText();

        // Crea una instancia de Categoria con los valores
        Categoria nuevaCategoria = new Categoria();
        nuevaCategoria.setNombreCategoria(nombreCategoria); 

        // Llama al método insertarCategoria de CategoriaDAO
        categoriaDAO.gestionarCategoria("I", 0, nombreCategoria);

        // Actualiza la tabla y limpia los campos
        actualizarTablaCategorias();
        limpiarCamposCategorias();
    }

    private void editarCategoria() {
        // Obtén los valores de los campos
        int idCategoria = obtenerIdCategoriaSeleccionada();
        String nombreCategoria = tfDescripcion.getText();

        // Crea una instancia de Categoria con los valores
        Categoria categoriaEditada = new Categoria();
        categoriaEditada.setIdCategoria(idCategoria);
        categoriaEditada.setNombreCategoria(nombreCategoria); 

        // Llama al método actualizarCategoria de CategoriaDAO
        categoriaDAO.gestionarCategoria("U", categoriaEditada.getIdCategoria(), categoriaEditada.getNombreCategoria());

        // Actualiza la tabla y limpia los campos
        actualizarTablaCategorias();
        limpiarCamposCategorias();
    }

    private void buscarCategoria() {
        // Obtén el nombre de la categoría a buscar
        String nombreCategoriaABuscar = tfDescripcion.getText();

        // Llama al método buscarCategoriaPorNombre de CategoriaDAO
        Categoria categoriaEncontrada = categoriaDAO.buscarCategoriaPorNombre(nombreCategoriaABuscar);

        if (categoriaEncontrada != null) {
            // Muestra la descripción en tfDescripcion
            tfDescripcion.setText(categoriaEncontrada.getNombreCategoria());

            // Actualiza la tabla para resaltar la categoría encontrada
            resaltarCategoriaEnTabla(nombreCategoriaABuscar);
        } else {
            // Limpiar tfDescripcion si no se encuentra la categoría
            tfDescripcion.setText("");
        }
    }

    private void borrarCategoria() {
        // Obtén el ID de la categoría seleccionada
        int idCategoria = obtenerIdCategoriaSeleccionada();

        // Llama al método eliminarCategoria de CategoriaDAO
        categoriaDAO.gestionarCategoria("D", idCategoria, "");

        // Actualiza la tabla y limpia los campos
        actualizarTablaCategorias();
        limpiarCamposCategorias();
    }

    private void mostrarDescripcionCategoriaSeleccionada() {
        // Obtén el nombre de la categoría seleccionada
        String nombreCategoriaSeleccionada = obtenerNombreCategoriaSeleccionada();

        // Llama al método obtenerDescripcionCategoriaPorNombre de CategoriaDAO
        String descripcion = categoriaDAO.obtenerDescripcionCategoriaPorNombre(nombreCategoriaSeleccionada);

        // Muestra la descripción en tfDescripcion
        tfDescripcion.setText(descripcion);
    }

    private void actualizarTablaCategorias() {
        // Limpia la tabla antes de cargar nuevos datos
        modeloTablaCategorias.clear();

        // Carga nuevos datos desde la base de datos
        List<Categoria> categorias = categoriaDAO.obtenerCategoriasDesdeBaseDeDatos();

        // Agrega las nuevas filas a la tabla
        for (Categoria categoria : categorias) {
            modeloTablaCategorias.addRow(new Object[]{categoria.getIdCategoria(), categoria.getNombreCategoria()});
        }
    }

    private void limpiarCamposCategorias() {
        // Limpia los campos de texto
        tfDescripcion.setText("");
    }

    private int obtenerIdCategoriaSeleccionada() {
        // Obtén el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tablaCategorias.getSelectedRow();

        // Obtiene el ID de la categoría en la fila seleccionada
        return (int) modeloTablaCategorias.getValueAt(filaSeleccionada, 0);
    }

    private String obtenerNombreCategoriaSeleccionada() {
        // Obtén el índice de la fila seleccionada en la tabla
        int filaSeleccionada = tablaCategorias.getSelectedRow();

        // Obtiene el nombre de la categoría en la fila seleccionada
        return (String) modeloTablaCategorias.getValueAt(filaSeleccionada, 1);
    }

    private void resaltarCategoriaEnTabla(String nombreCategoria) {
        // Itera sobre las filas de la tabla
        for (int i = 0; i < tablaCategorias.getRowCount(); i++) {
            // Obtiene el nombre de la categoría en la fila actual
            String nombreEnFila = (String) modeloTablaCategorias.getValueAt(i, 1);

            // Compara el nombre de la categoría en la fila actual con el nombre buscado
            if (nombreEnFila.equals(nombreCategoria)) {
                // Selecciona la fila y sale del bucle
                tablaCategorias.setRowSelectionInterval(i, i);
                break;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables
}
