/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofase3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author fping
 */
public class frmProductos extends javax.swing.JFrame {
    private ProductoDAO productoDAO;
    private ProductoTableModel productoTableModel;
    private int idProductoSeleccionado;
    private CategoriaTableModel modelCategorias;
    private CategoriaDAO categoriaDAO;
    Producto2 productoSeleccionado;
    
    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
        try {
            Connection conexion = obtenerConexion();  // Método que obtiene la conexión a la base de datos
            productoDAO = new ProductoDAO(conexion);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            // Puedes manejar el error de conexión de la manera que prefieras
        }
        
        cargarDatos();
        
        tablaProductos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Obtener la fila seleccionada
                    int filaSeleccionada = tablaProductos.getSelectedRow();
                    
                    if (filaSeleccionada > -1) {
                        // Actualizar los campos con los datos del producto seleccionado
                        actualizarCamposDesdeTabla(filaSeleccionada);
                    }
                    
                }
            }
        });
        llenarComboBoxCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAgregar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        cbCategorias = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        tfNombreProducto = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        tfPrecio = new javax.swing.JTextField();
        lblExistencia = new javax.swing.JLabel();
        tfExistencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productos");
        setBackground(new java.awt.Color(204, 255, 255));

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCategoria.setText("Categoria");

        lblNombreProducto.setText("Nombre Producto");

        lblDescripcion.setText("Descripción");

        lblPrecio.setText("Precio");

        lblExistencia.setText("Existencia");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreProducto)
                            .addComponent(tfNombreProducto)))
                    .addComponent(tfDescripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfExistencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPrecio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblExistencia)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbCategorias)
                    .addComponent(tfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblExistencia))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfExistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(tfPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        agregarProducto();
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        editarProducto(productoSeleccionado);
    }//GEN-LAST:event_bEditarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        buscarProducto();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        borrarProducto(productoSeleccionado);
    }//GEN-LAST:event_bBorrarActionPerformed

    private void actualizarCamposDesdeTabla(int filaSeleccionada) {
        // Obtener el producto desde el modelo basado en la fila seleccionada
        ProductoTableModel modelo = (ProductoTableModel) tablaProductos.getModel();
        productoSeleccionado = modelo.getProductoAt(filaSeleccionada);

        // Actualizar los campos con los datos del producto
        idProductoSeleccionado = productoSeleccionado.getIdProducto();
        tfNombreProducto.setText(productoSeleccionado.getNombreProducto());
        tfDescripcion.setText(productoSeleccionado.getDescripcion());
        tfPrecio.setText(String.valueOf(productoSeleccionado.getPrecio()));
        tfExistencia.setText(String.valueOf(productoSeleccionado.getExistencia()));

        // Seleccionar la categoría en el ComboBox
        seleccionarCategoriaEnComboBox(cbCategorias, productoSeleccionado.getNombreCategoria());
    }

    public void seleccionarCategoriaEnComboBox(JComboBox<String> comboBox, String nombreCategoria) {
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) comboBox.getModel();

        for (int i = 0; i < model.getSize(); i++) {
            String categoria = model.getElementAt(i);
            if (categoria.equals(nombreCategoria)) {
                comboBox.setSelectedIndex(i);
                return; // Termina el bucle una vez que se encuentra la categoría
            }
        }
    }
    
    private List<Producto2> obtenerProductosDesdeBD() {
    // Lógica para obtener la lista de productos desde la base de datos
    // Utilizando el método consultarProducto de tu ProductoDAO
        return productoDAO.consultarProductoTodos();  
    }
    
    private void cargarDatos() {
        List<Producto2> productos = obtenerProductosDesdeBD();
        productoTableModel = new ProductoTableModel(productos);
        tablaProductos.setModel(productoTableModel);
    }
    
    private Connection obtenerConexion() throws SQLException {
        // URL de conexión a la base de datos
        String url = "jdbc:sqlserver://DESKTOP-OKOLF5L\\BDD1;databaseName=proyectoisfase2";
        String usuario = "proyectoFase2";
        String contrasena = "proyectoFase2.";

        // Establecer la conexión
        return DriverManager.getConnection(url, usuario, contrasena);
    }
    
    // Método para llenar el JComboBox de categorías
    public void llenarComboBoxCategorias() {
        modelCategorias = new CategoriaTableModel();
        // Obtener la lista de nombres de categorías desde el modelo
        List<String> nombresCategorias = modelCategorias.obtenerNombresCategorias();

        // Crear un modelo para el JComboBox
        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>(nombresCategorias.toArray(new String[0]));

        // Asignar el modelo al JComboBox
        cbCategorias.setModel(comboModel);
    }
    
  // Método para obtener el idCategoria seleccionado del combo
    private int obtenerIdCategoriaSeleccionado() {
        // Obtén el objeto seleccionado del combo
        Object selectedItem = cbCategorias.getSelectedItem();

        // Si el objeto seleccionado es una instancia de String (nombrecategoria), busca el id en la lista de productos
        if (selectedItem instanceof String) {
            String nombreCategoriaSeleccionada = (String) selectedItem;
            return productoDAO.obtenerIdCategoriaPorNombre(nombreCategoriaSeleccionada);
        }

        // Manejar otros casos si es necesario
        return 0; // O algún valor predeterminado
    }  
    
   private void agregarProducto() {
        try {
            // Obtén los valores de los campos
            int idCategoria = obtenerIdCategoriaSeleccionado(); 
            String nombreProducto = tfNombreProducto.getText();
            String descripcion = tfDescripcion.getText();
            double precio = Double.parseDouble(tfPrecio.getText()); 
            int existencia = Integer.parseInt(tfExistencia.getText());

            // Llama al método insertarProducto de ProductoDAO
            productoDAO.insertarProducto(idCategoria, nombreProducto, descripcion, precio, null, existencia);

            // Actualiza la tabla y limpia los campos
            cargarDatos();
            limpiarCampos();
        } catch (NumberFormatException e) {
            // Manejar la excepción si los valores numéricos no son válidos
            JOptionPane.showMessageDialog(null, "Los valores numéricos no son válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
   
   // Métodos editarProducto, buscarProducto y borrarProducto siguen una estructura similar
   private void editarProducto(Producto2 productoSeleccionado) {
        if (productoSeleccionado != null) {
            // Obtén los valores de los campos
            int idProducto = productoSeleccionado.getIdProducto();
            int idCategoria = productoSeleccionado.getIdCategoria();
            String nombreProducto = tfNombreProducto.getText();
            String descripcion = tfDescripcion.getText();
            double precio = Double.parseDouble(tfPrecio.getText()); 
            int existencia = Integer.parseInt(tfExistencia.getText());

            // Actualiza el producto utilizando el método actualizarProducto de ProductoDAO
            productoDAO.actualizarProducto(idProducto, idCategoria, nombreProducto, descripcion, precio, null, existencia);

            // Actualiza la tabla y limpia los campos
            cargarDatos();
            limpiarCampos();
        } else {
            // Muestra un mensaje indicando que no se ha seleccionado ningún producto
            JOptionPane.showMessageDialog(this, "Selecciona un producto para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

   private void borrarProducto(Producto2 productoSeleccionado) {
        
        // Llama al método eliminarProducto de ProductoDAO
        productoDAO.eliminarProducto(productoSeleccionado.getIdProducto());

        // Actualiza la tabla y limpia los campos
        cargarDatos();
        limpiarCampos();
    }
   
   private void buscarProducto() {
        // Obtén el nombre del producto a buscar
        String nombreProductoBuscar = tfNombreProducto.getText().trim();

        // Verifica si el nombre del producto a buscar no está vacío
        if (!nombreProductoBuscar.isEmpty()) {
            // Obtén el modelo de la tabla
            ProductoTableModel modelo = (ProductoTableModel) tablaProductos.getModel();

            // Obtén la lista de productos del modelo
            List<Producto2> productos = obtenerProductosDesdeBD();

            // Busca el producto en la lista por el nombre
            Optional<Producto2> productoEncontrado = productos.stream()
                    .filter(producto -> producto.getNombreProducto().equalsIgnoreCase(nombreProductoBuscar))
                    .findFirst();

            // Verifica si se encontró el producto
            if (productoEncontrado.isPresent()) {
                // Obtén el índice de la fila en la tabla
                int rowIndex = productos.indexOf(productoEncontrado.get());

                // Resalta la fila en la tabla
                resaltarFilaEnTabla(rowIndex);
            } else {
                // Muestra un mensaje indicando que el producto no fue encontrado
                JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            // Muestra un mensaje indicando que el campo de búsqueda está vacío
            JOptionPane.showMessageDialog(this, "Ingresa el nombre del producto a buscar.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void resaltarFilaEnTabla(int rowIndex) {
        // Obtén el modelo de la tabla
        ProductoTableModel modelo = (ProductoTableModel) tablaProductos.getModel();

        // Obtén el sorter de la tabla
        RowSorter<? extends TableModel> sorter = tablaProductos.getRowSorter();

        // Convierte el índice de la fila al índice de la fila en el modelo
        int modelRowIndex = tablaProductos.convertRowIndexToModel(rowIndex);

        // Selecciona y resalta la fila en la tabla
        tablaProductos.setRowSelectionInterval(modelRowIndex, modelRowIndex);

        // Desplaza la vista de la tabla para mostrar la fila seleccionada
        tablaProductos.scrollRectToVisible(tablaProductos.getCellRect(modelRowIndex, 0, true));
    }

    // Método para limpiar los campos
    private void limpiarCampos() {
        tfNombreProducto.setText("");
        tfDescripcion.setText("");
        tfPrecio.setText("");
        tfExistencia.setText("");
        cbCategorias.setSelectedIndex(0); // O el índice deseado para la opción predeterminada
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfExistencia;
    private javax.swing.JTextField tfNombreProducto;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
